apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t7mxycaoz-python 
  janus-idp.io/tekton: t7mxycaoz-python
  backstage.io/kubernetes-id: t7mxycaoz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t7mxycaoz-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml